---

- name: Restart k3s-agent
  become: yes
  service:
    name: k3s-agent
    state: restarted
    enabled: yes

- name: Wait for node become ready
  become: yes
  shell: 'kubectl wait --for=condition=Ready node/{{ ansible_fqdn }}'
  delegate_to: '{{ groups.pi_kube_masters|first }}'
  ignore_errors: yes
