---

- name: Install iptables-persistent
  apt: name=iptables-persistent state=present

- name: Ensure netfilter-persistent enabled
  service:
    name: netfilter-persistent
    enabled: yes

- name: Setup IP forwarding
  copy:
    src: local-router.conf
    dest: /etc/sysctl.d/
