---
- hosts: pi_kube
  vars:
    k3s_version: v1.20.4+k3s1
  roles:
    - k3s

- hosts: pi_kube_servers
  serial: 1
  roles:
    - k3s/master

- hosts: pi_kube_workers
  serial: 1
  roles:
    - k3s/worker
